spring:
  application:
    name: yu-ai-code-mother-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_arc
    username: root
    password: root
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 3600
      password:
      database: 0
  # session
  session:
    store-type: redis
    # 过期时间为30天
    timeout: 2592000
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.arceuid.yuaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
