spring:
  application:
    name: yu-ai-code-mother-backend
server:
  port: 8080
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.arceuid.yuaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
